 CREATE TABLE SALES_DATA(
	REGION VARCHAR(50),
	PRODUCT VARCHAR(50),
	SALES_AMOUNT INT,
	YEAR INT
)

INSERT INTO SALES_DATA values
('North America', 'Watch', 1500, 2023),
('Europe', 'Mobile', 1200, 2023),
('Asia', 'Watch', 1800, 2023),
('North America', 'TV', 900, 2024),
('Europe', 'Watch', 2000, 2024),
('Asia', 'Mobile', 1000, 2024),
('North America', 'Mobile', 1600, 2023),
('Europe', 'TV', 1500, 2023),
('Asia', 'TV', 1100, 2024),
('North America', 'Watch', 1700, 2024)

select * from SALES_DATA

--Part – A:
--1. Display Total Sales Amount by Region.
SELECT REGION ,SUM(SALES_AMOUNT)AS 'TOTAL AMOUNT' FROM SALES_DATA GROUP BY REGION

--2. Display Average Sales Amount by Product
SELECT AVG(SALES_AMOUNT) AS AVGSALES FROM SALES_DATA GROUP BY PRODUCT

--3. Display Maximum Sales Amount by Year
SELECT MAX(SALES_AMOUNT) AS MAXSALES FROM SALES_DATA GROUP BY YEAR

--4. Display Minimum Sales Amount by Region and Year
SELECT REGION,MIN(SALES_AMOUNT) AS MINSALES FROM SALES_DATA GROUP BY REGION,YEAR

--5. Count of Products Sold by Region
SELECT REGION,AVG(SALES_AMOUNT) AS AVGSALES FROM SALES_DATA GROUP BY REGION


--6. Display TOTAL Sales Amount by Year and Product
SELECT SUM(SALES_AMOUNT) AS SUMSALES FROM SALES_DATA GROUP BY YEAR,PRODUCT

--7. Display Regions with Total Sales Greater Than 5000
SELECT SUM(SALES_AMOUNT),REGION FROM SALES_DATA
GROUP BY REGION
HAVING SUM(SALES_AMOUNT)>5000


--8. Display Products with Average Sales Less Than 10000
SELECT PRODUCT,SUM(SALES_AMOUNT) FROM SALES_DATA
GROUP BY PRODUCT
HAVING SUM(SALES_AMOUNT)<10000

--9. Display Years with Maximum Sales Exceeding 500
SELECT MAX(SALES_AMOUNT) FROM SALES_DATA
GROUP BY YEAR
HAVING MAX(SALES_AMOUNT)>500

--10. Display Regions with at Least 3 Distinct Products Sold.
SELECT REGION, COUNT(DISTINCT PRODUCT) FROM SALES_DATA
GROUP BY REGION
HAVING COUNT(DISTINCT PRODUCT)>3 


--11. Display Years with Minimum Sales Less Than 1000
SELECT YEAR,MIN(SALES_AMOUNT) FROM SALES_DATA
GROUP BY YEAR
HAVING MIN(SALES_AMOUNT)<1000 



--12. Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount
SELECT SUM(SALES_AMOUNT) AS TOTALAMOUNT,REGION FROM SALES_DATA
WHERE YEAR='2023'
GROUP BY REGION
ORDER BY SUM(SALES_AMOUNT)





SELECT REGION,COUNT(SALES_AMOUNT) AS TOTAL FROM SALES_DATA
GROUP BY REGION

SELECT ADATE,AVG(SALES_AMOUNT) AS AVGSALES FROM SALES_DATA
GROUP BY PRODUCT

SELECT ADATE,MAX(SALES_AMOUNT) AS MAXSALES FROM SALES_DATA
GROUP BY ADATE

SELECT ADATE,REGION,MIN(SALES_AMOUNT) AS MINSALES FROM SALES_DATA
GROUP BY REGION,ADATE

SELECT REGION,COUNT(SALES_AMOUNT) AS TOTALSALES FROM SALES_DATA
GROUP BY REGION

SELECT SUM(SALES_AMOUNT),ADATE,PRODUCT FROM SALES_DATA
GROUP BY ADATE,PRODUCT







------B------------
SELECT COUNT(SALES_AMOUNT),ADATE,REGION FROM SALES_DATA
GROUP BY ADATE,REGION
ORDER BY ADATE,REGION

select MAX(SALES_AMOUNT),REGION FROM SALES_DATA

GROUP BY REGION
HAVING MAX(SALES_AMOUNT)>1000


SELECT ADATE,SUM(SALES_AMOUNT) FROM SALES_DATA
GROUP BY ADATE
HAVING SUM(SALES_AMOUNT)>1000
ORDER BY ADATE DESC

SELECT TOP 3 REGION FROM SALES_DATA
WHERE ADATE='2024'
