---Retrieve all data from table DEPOSIT.

SELECT * FROM DEPOSIT

SELECT * FROM BORROW

SELECT * FROM CUSTOMERS

SELECT  ACTNO,CNAME,AMOUNT FROM DEPOSIT

SELECT LOANNO,AMOUNT FROM BORROW

SELECT * FROM BORROW WHERE BNAME='ANDHERI'

SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO =106

SELECT * FROM BORROW WHERE AMOUNT>5000

SELECT * FROM DEPOSIT WHERE ADATE>'1-DEC-1996'

SELECT * FROM DEPOSIT WHERE ACTNO<105

SELECT * FROM CUSTOMERS WHERE CNAME ='NAGPUR' OR CNAME ='DELHI'

SELECT * FROM CUSTOMERS WHERE CNAME IN('NAGPUR','DELHI')

SELECT * FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105

SELECT * FROM BORROW WHERE AMOUNT>=3000AND AMOUNT<=8000

SELECT * FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000

SELECT * FROM DEPOSIT WHERE BNAME!='ANDHERI'

SELECT ACTNO,BNAME,AMOUNT FROM DEPOSIT WHERE BNAME IN('AJNI','KAROLBAGH','M.G.ROAD')AND ACTNO<104

